# Generated by Django 5.0 on 2023-12-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя')),
                ('old', models.CharField(max_length=3, verbose_name='Возраст')),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('-name', '-old'),
            },
        ),
    ]
