# Generated by Django 5.0 on 2023-12-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=10, verbose_name='Имя')),
                ('report_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Имя')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
