# Generated by Django 5.0 on 2024-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_report_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Жалоба'),
        ),
    ]
