# Generated by Django 5.0 on 2024-01-01 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_report_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
